# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 220)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Format = QtWidgets.QFrame(self.centralwidget)
        self.Format.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Format.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Format.setObjectName("Format")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Format)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditWidget = QtWidgets.QWidget(self.Format)
        self.lineEditWidget.setObjectName("lineEditWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.lineEditWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.lineEditWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.lineEditWidget)
        self.confirmWidget = QtWidgets.QWidget(self.Format)
        self.confirmWidget.setObjectName("confirmWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.confirmWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.confirmButton = QtWidgets.QPushButton(self.confirmWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_3.addWidget(self.confirmButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.confirmWidget)
        self.horizontalLayout.addWidget(self.Format)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 341, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreference = QtWidgets.QAction(MainWindow)
        self.actionPreference.setObjectName("actionPreference")
        self.menuSettings.addAction(self.actionPreference)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionPreference.setText(_translate("MainWindow", "Preference"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
